config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'doctors/doctoradmin'
  get 'welcome/index'
  get 'mascota/agregarTratamiento'
  resources :tratamientos
  resources :medicamentos
  resources :receta
  resources :mascota
  resources :doctors
  resources :duenios
 
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/duenio.rb
class Duenio < ApplicationRecord
    has_one_attached :image, :dependent => :delete_all

end

app/controllers/duenios_controller.rb
class DueniosController < ApplicationController
  before_action :set_duenio, only: [:show, :edit, :update, :destroy]

  # GET /duenios
  # GET /duenios.json
  def index
    @duenios = Duenio.all
  end

  # GET /duenios/1
  # GET /duenios/1.json
  def show
    @mascotas=Mascotum.where("duenio_id=?", @duenio.id)

  end

  # GET /duenios/new
  def new
    @duenio = Duenio.new
  end

  # GET /duenios/1/edit
  def edit
  end

  # POST /duenios
  # POST /duenios.json
  def create
    @duenio = Duenio.new(duenio_params)

    respond_to do |format|
      if @duenio.save
        format.html { redirect_to @duenio, notice: 'Duenio was successfully created.' }
        format.json { render :show, status: :created, location: @duenio }
      else
        format.html { render :new }
        format.json { render json: @duenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /duenios/1
  # PATCH/PUT /duenios/1.json
  def update
    respond_to do |format|
      if @duenio.update(duenio_params)
        format.html { redirect_to @duenio, notice: 'Duenio was successfully updated.' }
        format.json { render :show, status: :ok, location: @duenio }
      else
        format.html { render :edit }
        format.json { render json: @duenio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /duenios/1
  # DELETE /duenios/1.json
  def destroy
    mascotas=Mascotum.where("duenio_id=?",@duenio.id)
    mascotas.each do |m|
      m.destroy
    end 
    @duenio.destroy
    respond_to do |format|
      format.html { redirect_to duenios_url, notice: 'Duenio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duenio
      @duenio = Duenio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duenio_params
      params.require(:duenio).permit(:nombre, :direccion, :image)
    end
end

app/helpers/duenios_helper.rb
module DueniosHelper
end

app/views/duenios/_form.html.erb
<%= form_with(model: duenio, local: true) do |form| %>
  <% if duenio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(duenio.errors.count, "error") %> prohibited this duenio from being saved:</h2>

      <ul>
      <% duenio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <div class="form-group row">
    <%= form.label :nombre, class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
    <%= form.text_field :nombre, class:"form-control"  %>
    </div>
  </div>
</div>

 <div class="field">
  <div class="form-group row">
    <%= form.label :direccion, class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
    <%= form.text_field :direccion, class:"form-control"  %>
    </div>
  </div>
</div>

  
 <div class="custom-file">

  <div class="field">
    <%= form.label :image, "Imagen del dueño", class:"custom-file-label"  %>
    <%= form.file_field :image, class:"custom-file-input", required: true %>
  </div>
  </div>
  <br>
    <br>

  <div class="actions">
    <%= form.submit "Registrar", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/duenios/edit.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container text-center bg-light">

<h1>Editar al dueño <%= @duenio.nombre%></h1>

<%= render 'form', duenio: @duenio %>
<%= link_to 'Detalles actuales', @duenio %> |
<%= link_to 'atras', duenios_path %>
</div>

app/views/duenios/index.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<div class="container text-center bg-light">
<h1 class="display-1">Clientes</h1>
<div  class="text-center ">
  <h1 class="display-4"> Actualmente existen <%= Duenio.all.count %> clientes registrados</h1> 
  <a href="<%= new_duenio_url%>" class="btn btn-primary">Registrar un nuevo cliente</a>
</div>
<br>
<br>
 <div class="row">
    <% @duenios.each do |duenio| %>
      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
        <img src="<%= url_for(duenio.image)%>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Clave: <%= duenio.id %></h5>
          <p class="card-text"><%= duenio.nombre %></p>
          <p class="card-text"><%= duenio.direccion %></p>
          <a href="<%= url_for(duenio)%>" class="btn btn-primary">Detalles</a>
          <%= link_to 'Eliminar', duenio, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
  
        </div>
      </div>
      </div>
    <% end %>
 </div>
<br>
</div>

app/views/duenios/new.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container text-center bg-light">

<h1>Registrar un nuevo cliente</h1>

<%= render 'form', duenio: @duenio %>

<%= link_to 'atras', duenios_path %>
</div>

app/views/duenios/show.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<br>
<div class="container text-center bg-light">

<h1>Datos del cliente <%= @duenio.nombre%></h1>
  
  <p>
    <strong>Clave:</strong>
    <%= @duenio.id %>
  </p>
  <p>
    <strong>Nombre:</strong>
    <%= @duenio.nombre %>
  </p>
  <p>
    <strong>Direccion:</strong>
    <%= @duenio.direccion %>
  </p>

  <div class="card bg-dark text-white">
  <img src="<%= url_for(@duenio.image)%>" class="card-img" alt="...">
  <div class="card-img-overlay">
    
  </div>
</div>
<br>
<br>
<br>

  <%= link_to 'Editar datos', edit_duenio_path(@duenio), class:"btn btn-secondary" %> |
  <%= link_to 'Atras', duenios_path, class:"btn btn-primary" %>
 
  
<br>
<br>
<br>
<h1 class="display-4">Este cliente tiene actualmente <%= @mascotas.count %> mascotas registradas</h1>
<div class="row">

    <% @mascotas.each do |mascota| %>

      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
        <img src="<%= url_for(mascota.image)%>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Clave de la mascota: <%= mascota.id %></h5>
          <p class="card-text"><%= mascota.nombre %></p>
                    <%= link_to 'Detalles', mascota, class:"btn btn-primary" %>

        </div>
      </div>
      </div>

    <% end %>
</div>
</div>