config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'doctors/doctoradmin'
  get 'welcome/index'
  get 'mascota/agregarTratamiento'
  resources :tratamientos
  resources :medicamentos
  resources :receta
  resources :mascota
  resources :doctors
  resources :duenios
 
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/medicamento.rb
class Medicamento < ApplicationRecord
end

app/controllers/medicamentos_controller.rb
class MedicamentosController < ApplicationController
  before_action :set_medicamento, only: [:show, :edit, :update, :destroy]

  # GET /medicamentos
  # GET /medicamentos.json
  def index
    @medicamentos = Medicamento.all
  end

  # GET /medicamentos/1
  # GET /medicamentos/1.json
  def show
  end

  # GET /medicamentos/new
  def new
    @medicamento = Medicamento.new
  end

  # GET /medicamentos/1/edit
  def edit
  end

  # POST /medicamentos
  # POST /medicamentos.json
  def create
    @medicamento = Medicamento.new(medicamento_params)

    respond_to do |format|
      if @medicamento.save
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully created.' }
        format.json { render :show, status: :created, location: @medicamento }
      else
        format.html { render :new }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicamentos/1
  # PATCH/PUT /medicamentos/1.json
  def update
    respond_to do |format|
      if @medicamento.update(medicamento_params)
        format.html { redirect_to @medicamento, notice: 'Medicamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicamento }
      else
        format.html { render :edit }
        format.json { render json: @medicamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicamentos/1
  # DELETE /medicamentos/1.json
  def destroy
    @medicamento.destroy
    respond_to do |format|
      format.html { redirect_to medicamentos_url, notice: 'Medicamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicamento
      @medicamento = Medicamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicamento_params
      params.require(:medicamento).permit(:Nombre, :laboratorio, :gramaje)
    end
end

app/helpers/medicamentos_helper.rb
module MedicamentosHelper
end

app/views/medicamentos/_form.html.erb
<%= form_with(model: medicamento, local: true) do |form| %>
  <% if medicamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicamento.errors.count, "error") %> prohibited this medicamento from being saved:</h2>

      <ul>
      <% medicamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :Nombre %>
  </div>

  <div class="field">
    <%= form.label :laboratorio %>
    <%= form.text_field :laboratorio %>
  </div>

  <div class="field">
    <%= form.label :gramaje %>
    <%= form.text_field :gramaje %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/medicamentos/edit.html.erb
<h1>Editing Medicamento</h1>

<%= render 'form', medicamento: @medicamento %>

<%= link_to 'Show', @medicamento %> |
<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Medicamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Laboratorio</th>
      <th>Gramaje</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medicamentos.each do |medicamento| %>
      <tr>
        <td><%= medicamento.Nombre %></td>
        <td><%= medicamento.laboratorio %></td>
        <td><%= medicamento.gramaje %></td>
        <td><%= link_to 'Show', medicamento %></td>
        <td><%= link_to 'Edit', edit_medicamento_path(medicamento) %></td>
        <td><%= link_to 'Destroy', medicamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medicamento', new_medicamento_path %>

app/views/medicamentos/new.html.erb
<h1>New Medicamento</h1>

<%= render 'form', medicamento: @medicamento %>

<%= link_to 'Back', medicamentos_path %>

app/views/medicamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @medicamento.Nombre %>
</p>

<p>
  <strong>Laboratorio:</strong>
  <%= @medicamento.laboratorio %>
</p>

<p>
  <strong>Gramaje:</strong>
  <%= @medicamento.gramaje %>
</p>

<%= link_to 'Edit', edit_medicamento_path(@medicamento) %> |
<%= link_to 'Back', medicamentos_path %>