config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'doctors/doctoradmin'
  get 'welcome/index'
  get 'mascota/agregarTratamiento'
  resources :tratamientos
  resources :medicamentos
  resources :receta
  resources :mascota
  resources :doctors
  resources :duenios
 
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_one_attached :image, :dependent => :delete_all
    
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    if current_user==nil
      @doctors = Doctor.all
    else
      redirect_to doctors_doctoradmin_path
    end 
    
  end

  def doctoradmin
    if current_user!=nil
      @doctors = Doctor.all
    else
      redirect_to root_path
    end    
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @mascotas=Mascotum.where("doctor_id=?", @doctor.id)
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    mascotas=Mascotum.where("doctor_id=?",@doctor.id)
    mascotas.each do |m|
      m.destroy
    end  
    mascotas=Recetum.where("doctor_id=?",@doctor.id)
    mascotas.each do |m|
      m.destroy
    end  

    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:nombre, :image)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <div class="form-group row">
    <%= form.label :nombre, class:"col-sm-2 col-form-label"  %>
    <div class="col-sm-10">
    <%= form.text_field :nombre, class:"form-control"  %>
    </div>
  </div>
</div>
  <div class="custom-file">

  <div class="field">
    <%= form.label :image, "Imagen del doctor", class:"custom-file-label"   %>
    <%= form.file_field :image, class:"custom-file-input", required: true  %>
  </div>
  </div>
  <br>
    <br>

  <div class="actions">
    <%= form.submit "Registrar", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/doctors/doctoradmin.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<div class="container text-center bg-light">
<h1 class="display-1">Nuestros doctores</h1>
<div  class="text-center ">
  <h1 class="display-4"> Actualmente existen <%= Doctor.all.count %> doctores registrados</h1> 
  <a href="<%= new_doctor_url%>" class="btn btn-primary">Registrar un nuevo doctor</a>
</div>
<br>
<br>
 <div class="row">
    <% @doctors.each do |doctor| %>
      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
        <img src="<%= url_for(doctor.image)%>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Clave: <%= doctor.id %></h5>
          <p class="card-text"><%= doctor.nombre %></p>
          <a href="<%= url_for(doctor)%>" class="btn btn-primary">Detalles</a>
         <%= link_to 'Eliminar', doctor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
        </div>
      </div>
      </div>
    <% end %>
 </div>
<br>
</div>

app/views/doctors/edit.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container text-center bg-light">

<h1>Editar al doctor <%= @doctor.nombre%></h1>

<%= render 'form', doctor: @doctor %>
<%= link_to 'Detalles actuales', @doctor %> |
<%= link_to 'atras', doctors_doctoradmin_path %>
</div>

app/views/doctors/index.html.erb
<%= render "layouts/header" %>

<br>

<br>
<div class="container text-center bg-light">
<p id="notice"><%= notice %></p>

<h1 class="display-1">Nuestros doctores</h1>
<div  class="text-center ">
  <p>En M&A nos preocupamos por la seguridad y por la salud de nuestras mascotas, por eso les presentamos una lista con nuestros doctores veterinarios altamente capacitados, para que usted y su familia puedan estar tranquilos con la integridad de sus mascotas</p>
  <h1 class="display-4"> Actualmente contamos con <%= Doctor.all.count %> doctores</h1> 

</div>


     <div class="row">



    <% @doctors.each do |doctor| %>

      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
        <img src="<%= url_for(doctor.image)%>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Clave del doctor: <%= doctor.id %></h5>
          <p class="card-text"><%= doctor.nombre %></p>
          <p class="card-text">Este doctor atiende actualmente <%= Mascotum.where("doctor_id=?",doctor.id).count %> mascotas</p>

        </div>
      </div>
      </div>
      
      
  

      
      

    <% end %>

  </div>
<br>

</div>

app/views/doctors/new.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container text-center bg-light">

<h1>Registrar un nuevo doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'atras', doctors_doctoradmin_path %>
</div>

app/views/doctors/show.html.erb
<%= render "layouts/headerad" %>
<br>
<br>
<br>
<div class="container text-center bg-light">

<h1>Datos del doctor <%= @doctor.nombre%></h1>
  
  <p>
    <strong>Clave:</strong>
    <%= @doctor.id %>
  </p>
  <p>
    <strong>Nombre:</strong>
    <%= @doctor.nombre %>
  </p>

  <div class="card bg-dark text-white">
  <img src="<%= url_for(@doctor.image)%>" class="card-img" alt="...">
  <div class="card-img-overlay">
    
  </div>
</div>
<br>
<br>
<br>
<% if current_user!=nil%>
  <%= link_to 'Editar datos', edit_doctor_path(@doctor), class:"btn btn-secondary" %> |
  <%= link_to 'Atras', doctors_doctoradmin_path, class:"btn btn-primary" %>
<%else%>  
  <%= link_to 'Atras', doctors_path, class:"btn btn-primary" %>
<%end%>  
  
<br>
<br>
<br>
<h1 class="display-4">Este doctor atiende actualmente <%= @mascotas.count %> mascotas</h1>
<div class="row">

    <% @mascotas.each do |mascota| %>

      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
        <img src="<%= url_for(mascota.image)%>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Clave de la mascota: <%= mascota.id %></h5>
          <p class="card-text"><%= mascota.nombre %></p>
          <%= link_to 'Detalles', mascota, class:"btn btn-primary" %>
        </div>
      </div>
      </div>

    <% end %>
</div>
</div>