config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'doctors/doctoradmin'
  get 'welcome/index'
  get 'mascota/agregarTratamiento'
  resources :tratamientos
  resources :medicamentos
  resources :receta
  resources :mascota
  resources :doctors
  resources :duenios
 
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tratamiento.rb
class Tratamiento < ApplicationRecord
  belongs_to :receta,  optional: true
  belongs_to :medicamento,  optional: true
end

app/controllers/tratamientos_controller.rb
class TratamientosController < ApplicationController
  before_action :set_tratamiento, only: [:show, :edit, :update, :destroy]

  # GET /tratamientos
  # GET /tratamientos.json
  def index
    @tratamientos = Tratamiento.all
  end

  # GET /tratamientos/1
  # GET /tratamientos/1.json
  def show
  end

  # GET /tratamientos/new
  def new
    @tratamiento = Tratamiento.new
  end

  # GET /tratamientos/1/edit
  def edit
  end

  # POST /tratamientos
  # POST /tratamientos.json
  def create
    @tratamiento = Tratamiento.new(tratamiento_params)

    respond_to do |format|
      if @tratamiento.save
        format.html { redirect_to @tratamiento, notice: 'Tratamiento was successfully created.' }
        format.json { render :show, status: :created, location: @tratamiento }
      else
        format.html { render :new }
        format.json { render json: @tratamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tratamientos/1
  # PATCH/PUT /tratamientos/1.json
  def update
    respond_to do |format|
      if @tratamiento.update(tratamiento_params)
        format.html { redirect_to @tratamiento, notice: 'Tratamiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @tratamiento }
      else
        format.html { render :edit }
        format.json { render json: @tratamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tratamientos/1
  # DELETE /tratamientos/1.json
  def destroy
    @tratamiento.destroy
    respond_to do |format|
      format.html { redirect_to tratamientos_url, notice: 'Tratamiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tratamiento
      @tratamiento = Tratamiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tratamiento_params
      params.require(:tratamiento).permit(:descripcion, :receta_id, :medicamento_id)
    end
end

app/helpers/tratamientos_helper.rb
module TratamientosHelper
end

app/views/tratamientos/_form.html.erb
<%= form_with(model: tratamiento, local: true) do |form| %>
  <% if tratamiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tratamiento.errors.count, "error") %> prohibited this tratamiento from being saved:</h2>

      <ul>
      <% tratamiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :receta_id %>
    <%= form.text_field :receta_id %>
  </div>

  <div class="field">
    <%= form.label :medicamento_id %>
    <%= form.text_field :medicamento_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tratamientos/edit.html.erb
<h1>Editing Tratamiento</h1>

<%= render 'form', tratamiento: @tratamiento %>

<%= link_to 'Show', @tratamiento %> |
<%= link_to 'Back', tratamientos_path %>

app/views/tratamientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tratamientos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Receta</th>
      <th>Medicamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tratamientos.each do |tratamiento| %>
      <tr>
        <td><%= tratamiento.descripcion %></td>
        <td><%= tratamiento.receta %></td>
        <td><%= tratamiento.medicamento %></td>
        <td><%= link_to 'Show', tratamiento %></td>
        <td><%= link_to 'Edit', edit_tratamiento_path(tratamiento) %></td>
        <td><%= link_to 'Destroy', tratamiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tratamiento', new_tratamiento_path %>

app/views/tratamientos/new.html.erb
<h1>New Tratamiento</h1>

<%= render 'form', tratamiento: @tratamiento %>

<%= link_to 'Back', tratamientos_path %>

app/views/tratamientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @tratamiento.descripcion %>
</p>

<p>
  <strong>Receta:</strong>
  <%= @tratamiento.receta %>
</p>

<p>
  <strong>Medicamento:</strong>
  <%= @tratamiento.medicamento %>
</p>

<%= link_to 'Edit', edit_tratamiento_path(@tratamiento) %> |
<%= link_to 'Back', tratamientos_path %>